---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: pull-req
    type: pull-request
    source:
      repo: fi3/pova-cd
      uri: git@github.com:Fi3/pova-cd.git
      base: master
      access_token: ((access-token))
      private_key: ((private-key))
  - name: git-master
    type: git
    source:
      uri: git@github.com:Fi3/pova-cd.git
      base: master
      private_key: ((private-key))

jobs:
 - name: test-pr
   plan:
   - get: pull-req
     trigger: true
     version: every
   - task: unit
     privileged: true
     config:
       image_resource:
         type: docker-image
         source: {repository: docker, tag: dind}
       inputs:
         - name: pull-req
       platform: linux
       params:
         DB_PATH: ((DB_PATH))
         DB_BACK_UP_PATH: ((DB_BACK_UP_PATH))
         BU_NAME: ((BU_NAME))
         REDIS_PORT: ((REDIS_PORT))
         REDIS_HOST: ((REDIS_HOST))
         HOST: ((HOST))
       run:
         path: docker-compose
         args: [run, web, pylint, ./src]
     on_success:
       put: pull-req
       params:
         path: pull-req
         status: success
     on_failure:
       put: pull-req
       params:
         path: pull-req
         status: failure
 - name: test-master
   plan:
   - get: git-master
     trigger: true
   - task: unit
     privileged: true
     config:
       image_resource:
         type: docker-image
         source: {repository: docker, tag: dind}
       inputs:
         - name: git-master
       platform: linux
       params:
         DB_PATH: ((DB_PATH))
         DB_BACK_UP_PATH: ((DB_BACK_UP_PATH))
         BU_NAME: ((BU_NAME))
         REDIS_PORT: ((REDIS_PORT))
         REDIS_HOST: ((REDIS_HOST))
         HOST: ((HOST))
       run:
         dir: /git-master/
         path: docker-compose
         args: [run, web, pylint, ./src]
