version: '3'
services:
  web:
    build: .
    environment:
     -  REDIS_PORT=${REDIS_PORT}
     -  REDIS_HOST=${REDIS_HOST}
     -  HOST=${HOST}
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
    volumes:
      - ${DB_PATH}:/data
